window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "APPDATA": "C:\\Users\\david.rondon\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_7216_JZXFMSAVCBRSAZPV",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "CO-IT022757",
  "ComSpec": "C:\\windows\\system32\\cmd.exe",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\windows\\notepad.exe",
  "EFC_9800": "0",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\david.rondon\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\david.rondon",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\david.rondon",
  "INIT_CWD": "C:\\Users\\david.rondon\\Documents\\Katas\\weather_app",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\david.rondon\\AppData\\Local",
  "LOGONSERVER": "\\\\CO-IT022757",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\david.rondon\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\david.rondon\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\david.rondon\\Documents\\Katas\\weather_app",
  "npm_config_node_gyp": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_npm_version": "10.2.5",
  "npm_config_prefix": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\david.rondon\\.npmrc",
  "npm_config_user_agent": "npm/10.2.5 node/v20.11.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "start",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\david.rondon\\Documents\\Katas\\weather_app\\package.json",
  "npm_package_name": "weather_app",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "8",
  "OneDrive": "C:\\Users\\david.rondon\\OneDrive - Globant",
  "OneDriveCommercial": "C:\\Users\\david.rondon\\OneDrive - Globant",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\david.rondon\\Documents\\Katas\\weather_app\\node_modules\\.bin;C:\\Users\\david.rondon\\Documents\\Katas\\node_modules\\.bin;C:\\Users\\david.rondon\\Documents\\node_modules\\.bin;C:\\Users\\david.rondon\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Users\\david.rondon\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\InvGate\\Insight Agent;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Users\\david.rondon\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\david.rondon\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\david.rondon\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8c01",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\david.rondon\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\MicrosoftManagedDesktop\\Powershell",
  "PUBLIC": "C:\\Users\\Public",
  "REACT_APP_MAPS_API": "AIzaSyBFQc5Fsc41VLHYJgL4_YvBBn_gv7neXbc",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\windows",
  "TEMP": "C:\\Users\\DAVID~1.RON\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.86.0",
  "TMP": "C:\\Users\\DAVID~1.RON\\AppData\\Local\\Temp",
  "USERDNSDOMAIN": "globant.com",
  "USERDOMAIN": "GLOBANT",
  "USERDOMAIN_ROAMINGPROFILE": "GLOBANT",
  "USERNAME": "david.rondon",
  "USERPROFILE": "C:\\Users\\david.rondon",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\david.rondon\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\david.rondon\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-8bed8a771c-sock",
  "VSCODE_INJECTION": "1",
  "windir": "C:\\windows",
  "ZES_ENABLE_SYSMAN": "1"
};