import React from 'react';
import './CityList.css';
import CityListElement from '../CityListElement/CityListElement';

function CityList() {
  return (
    <ul className='list' style={{ listStyleType: 'none', padding: 0 }}>
      {cities.map((item, index) => (
        <CityListElement key={index} name={item}></CityListElement>
      ))}
    </ul>
  );
}

export default CityList;

const cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'San Francisco',
  'Indianapolis',
  'Columbus',
  'Fort Worth',
  'Charlotte',
  'Seattle',
  'Denver',
  'El Paso',
  'Detroit',
  'Washington',
  'Boston',
  'Memphis',
  'Nashville',
  'Portland',
  'Oklahoma City',
  'Las Vegas',
  'Baltimore',
  'Louisville',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Mesa',
  'Kansas City',
  'Atlanta',
  'Long Beach',
  'Omaha',
  'Raleigh',
  'Colorado Springs',
  'Miami',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Arlington',
  'New Orleans',
  'Wichita',
  'Cleveland',
  'Tampa',
  'Bakersfield',
  'Aurora',
  'Anaheim',
  'Honolulu',
  'Santa Ana',
  'Riverside',
  'Corpus Christi',
  'Lexington',
  'Stockton',
  'Henderson',
  'Saint Paul',
  'St. Louis',
  'Cincinnati',
  'Pittsburgh',
  'Greensboro',
  'Anchorage',
  'Plano',
  'Lincoln',
  'Orlando',
  'Irvine',
  'Newark',
  'Toledo',
  'Durham',
  'Chula Vista',
  'Fort Wayne',
  'Jersey City',
  'St. Petersburg',
  'Laredo',
  'Madison',
  'Chandler',
  'Buffalo',
  'Lubbock',
  'Scottsdale',
  'Reno',
  'Glendale',
  'Gilbert',
  'Winston-Salem',
  'North Las Vegas',
  'Norfolk',
  'Chesapeake',
  'Garland',
  'Irving',
  'Hialeah',
  'Fremont',
  'Boise',
  'Richmond',
  'Baton Rouge',
  'Spokane',
  'Des Moines',
  'Tacoma',
  'San Bernardino',
  'Modesto',
  'Fontana',
  'Santa Clarita',
  'Birmingham',
  'Oxnard',
  'Fayetteville',
  'Moreno Valley',
  'Rochester',
  'Glendale',
  'Huntington Beach',
  'Salt Lake City',
  'Grand Rapids',
  'Amarillo',
  'Yonkers',
  'Aurora',
  'Montgomery',
  'Akron',
  'Little Rock',
  'Tempe',
  'Augusta',
  'Columbus',
  'Grand Prairie',
  'Shreveport',
  'Overland Park',
  'Tallahassee',
  'Mobile',
  'Port St. Lucie',
  'Knoxville',
  'Worcester',
  'Brownsville',
  'Vancouver',
  'Fort Lauderdale',
  'Sioux Falls',
  'Ontario',
  'Chattanooga',
  'Providence',
  'Newport News',
  'Rancho Cucamonga',
  'Santa Rosa',
  'Oceanside',
  'Salem',
  'Elk Grove',
  'Garden Grove',
  'Pembroke Pines',
  'Peoria',
  'Eugene',
  'Corona',
  'Cary',
  'Springfield',
  'Fort Collins',
  'Jackson',
  'Alexandria',
  'Hayward',
  'Lancaster',
  'Lakewood',
  'Clarksville',
  'Palmdale',
  'Salinas',
  'Springfield',
  'Hollywood',
  'Pasadena',
  'Sunnyvale',
  'Macon',
  'Kansas City',
  'Pomona',
  'Escondido',
  'Killeen',
  'Naperville',
  'Joliet',
  'Bellevue',
  'Rockford',
  'Savannah',
  'Paterson',
  'Torrance',
  'Bridgeport',
  'McKinney',
  'Mcallen',
  'Mesquite',
  'Syracuse',
  'Midland',
  'Pasadena',
  'Murfreesboro',
  'Miramar',
  'Dayton',
  'Fullerton',
  'Orange',
  'Concord',
  'Roseville',
  'Thornton',
  'Sterling Heights',
  'West Valley City',
  'Inglewood',
  'Oxnard',
  'Stamford',
  'Hartford',
  'Norman',
  'Clearwater',
  'Vallejo',
  'Manchester',
  'Rancho Cucamonga',
  'Wilmington',
  'High Point',
  'Round Rock',
  'West Jordan',
  'Billings',
  'Green Bay',
  'Fargo',
  'Everett',
  'Pueblo',
  'West Covina',
  'Wichita Falls',
  'Burbank',
  'Boulder',
  'Gresham',
  'Clovis',
  'Daly City',
  'Lakewood',
  'Santa Maria',
  'Hillsboro',
  'Sandy Springs',
  'Norwalk',
  'Jurupa Valley',
  'Lewisville',
  'Greeley',
  'Davie',
  'Westminster',
  'Woodbridge',
  'Denton',
  'Midland',
  'Philadelphia',
  'San Antonio',
  'Dallas',
  'Phoenix',
  'Houston',
  'San Diego',
  'Los Angeles',
  'New York',
  'Chicago',
  'San Francisco',
  'Miami',
  'Las Vegas',
  'Denver',
  'Seattle',
  'Orlando',
  'Boston',
  'Atlanta',
  'Washington',
  'Austin',
  'Philadelphia',
  'San Antonio',
  'Dallas',
  'Phoenix',
  'Houston',
  'San Diego',
  'Los Angeles',
  'New York',
  'Chicago',
  'San Francisco',
  'Miami',
  'Las Vegas',
  'Denver',
  'Seattle',
  'Orlando',
  'Boston',
  'Atlanta',
  'Washington',
  'Austin',
];
